jwt.secret.key=a8b3c9d2e1f4g7h0i5j8k2l6m9n4o1p7q0r3s5t8u2v6w9x1y4z7A0B3C6D9E2F5

# 1. Database ?? ?? (MySQL ??)
spring.datasource.url=jdbc:mysql://localhost:3306/expert
spring.datasource.username=root
spring.datasource.password=12345678
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 2. JPA/Hibernate ??
# ddl-auto=update? ??? ??? ?? ???? ???? ??/??.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect